### ISSUE TITLE
Unexpected behaviour of `lhs.vars` if a function is included in the left-hand side of a formula

### ISSUE THREAD

**Issue by GegznaV** [decisionpatterns/formula.tools#10]
The following code in which left-hand side contains a function (e.g., `log(Girth)`) returns a list while character vector is expected:

```r
rez <- lhs.vars(log(Girth) ~ Volume, data = trees)
class(rez)
```
```
[1] "terms"   "formula"
```

In the same situation `get.vars()` returns a list that is also either unexpected (or undocumented).

Is this behavior caused by a bug?

**Comment by ctbrown** [comment]
Hmm. Possibly.  Let me check it out.

**Comment by ctbrown** [comment]
This was never in the design of formula.tools ... to look for names outside of the data.  I am moving this to a enhancement/FR as this is probably something it should do.

**Comment by ctbrown** [comment]
This is fixed in the dev branch will be pushed to CRAN soon.
