### ISSUE TITLE
get.vars(NULL, NULL) throws an error but used to return NULL

### ISSUE THREAD

**Issue by pdbailey** [decisionpatterns/formula.tools#5]
Hi, 

Love the package, thanks for sharing it.

I'm having problems with get.vars with signature NULL. This comes up in a situation like this

     lhs.vars( ~ x)

which then calls `get.vars` on `lhs(~x)`. Since `lhs(~x)` returns NULL this leads to get.vars being called with signature `NULL`, `NULL` and this throws an error.

In prior versions this would work and return NULL, which makes sense to me.

I tried to look in the NEWS to see if this was an expected change but there is no entry for 1.5.

Thanks for your time!

Best,
Paul

**Comment by pdbailey** [comment]
I'll add that this following throws an error for the same reason.

get.vars( ~ a + b)

even if you think my call to get.lhs on a formula without a lhs is insane, I think the above is a reasonable call.

**Comment by ctbrown** [comment]
Thanks for reporting this; I will look at it tonight.  Thanks for using
formula.tools.

C-

**Comment by ctbrown** [comment]
Didn't get to this; will try before the weekend.

**Comment by pdbailey** [comment]
Probably the first thing to do is add a test. I'd go with

expect_that( get.vars(a ~ b + c), equals(c("a", "b", "c")))
expect_that( get.vars( ~ b + c), equals(c("b", "c")))

**Comment by pdbailey** [comment]
Looking at your code, it looks like you've already got the method to take care of this but it's commented out. This is lines 116-118 in get.vars.R

# setMethod( 'get.vars', c( 'ANY', 'ANY' ), 
#   function( x, data, ... ) NULL
# )

you could also do:

setMethod( 'get.vars', c( 'NULL', 'ANY' ), 
  function( x, data, ... ) NULL
)

**Comment by ctbrown** [comment]
Fixed in dev-1.5.3

**Comment by ctbrown** [comment]
Merged with master.

**Comment by ctbrown** [comment]
Submitted to CRAN. Fingers crossed; this issue.  Thanks Paul.
