### ISSUE TITLE
bug when assigning to empty lhs()

### ISSUE THREAD

**Issue by landroni** [decisionpatterns/formula.tools#6]
Using 1.5.4 I notice this bug when trying to assign `lhs()` in a one-sided formula: 

```
f <- ~ A   
lhs(f)     
## NULL
lhs(f) <- quote(B)
f
## ~B
```

The expected result would be `B ~ A`, but instead the right-hand side gets replaced. There are no such issues when there is already something in the left-hand side: 

```
f2 <- ZZZ ~ A   
lhs(f2) <- quote(B)
f2
## B ~ A
```

**Comment by landroni** [comment]
This probably happens because `lhs()` makes no check when the formula is of length 2: 

http://stackoverflow.com/questions/10154776/how-to-pass-the-right-hand-side-of-a-formula-to-another-formula/10155812#10155812

```
changeLHS <- function(formula, lhs) {
   if (length(formula) == 2) {
     formula[[3]] <- formula[[2]]
   }
   formula[[2]] <- substitute(lhs)
   formula
}

changeLHS(~ A, B)
## B ~ A
changeLHS(ZZZ ~ A, B)
## B ~ A
```

**Comment by ctbrown** [comment]
Indeed.  I will fix it when I get a chance.  Thanks for the issue.

C-
